/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_etterna_calc_jni_MinaCalcJNI */

#ifndef _Included_com_etterna_calc_jni_MinaCalcJNI
#define _Included_com_etterna_calc_jni_MinaCalcJNI
extern "C" {
/*
 * Class:     com_etterna_calc_jni_MinaCalcJNI
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_etterna_calc_jni_MinaCalcJNI_test
  (JNIEnv *, jobject);

}
#endif
