/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_etterna_calc_jni_MinaCalcJNI */

#ifndef _Included_com_etterna_calc_jni_MinaCalcJNI
#define _Included_com_etterna_calc_jni_MinaCalcJNI
extern "C" {
/*
 * Class:     com_etterna_calc_jni_MinaCalcJNI
 * Method:    getCalcVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_etterna_calc_jni_MinaCalcJNI_getCalcVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_etterna_calc_jni_MinaCalcJNI
 * Method:    minaSDCalc
 * Signature: (Ljava/lang/String;FF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_etterna_calc_jni_MinaCalcJNI_minaSDCalc
  (JNIEnv *, jobject, jstring, jfloat, jfloat);

}
#endif
