name: C/C++ CI
on:
  push:
    branches: [master]

jobs:
  linux-x64:
    name: Linux x64
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/setup-java@v2
        with:
          distributions: 'adopt'
          java-version: '11'

      - name: Configure
        run: ./configure

      - name: Make
        run: make lin

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/MinaCalcJNI.so

  windows:
    name: Windows x64
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/setup-java@v2
        with:
          distributions: 'adopt'
          java-version: '11'

      - name: Configure
        run: ./configure

      - name: Make
        run: make win

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/MinaCalcJNI.dll