name: C/C++ CI
on:
  push:
    branches: [master, '263']

env:
  CXX: g++
  CXXFLAGS: -g
  NATIVE: on
  TUNE: generic

jobs:
  linux-x64:
    name: Linux x64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: master
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Make
        run: cd master && make

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Linux x64 SO
          path: ${{github.workspace}}/master/MinaCalcJNI.so

  windows:
    name: Windows x64
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          path: master
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Make
        run: cd master && make

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Windows x64 DLL
          path: ${{github.workspace}}/master/MinaCalcJNI.dll